version: '3.7'

services:


  ####################################
  #### Banco de dados NoSQL
  ####################################
  mongodb:
    image: mongo:latest


  ####################################
  #### Aplicação
  ####################################
  application:
    image: marilia/examplespringboot:latest
    depends_on:
      - mongodb